const productos = [
	{
		id: 1,
		categoria: 'pisos',
		nombre: 'Carrara',
		medida: '60x120',
		caja: 1.44,
		precio: 5000,
		imagen: 'pisos/carrara.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 2,
		categoria: 'pisos',
		nombre: 'Onix',
		medida: '60x60',
		caja: 1.44,
		precio: 4200,
		imagen: 'pisos/onix.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 3,
		categoria: 'pisos',
		nombre: 'Bauhaus',
		medida: '58x58',
		caja: 1.35,
		precio: 2800,
		imagen: 'pisos/bauhaus.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 4,
		categoria: 'pisos',
		nombre: 'Linen',
		medida: '60x60',
		caja: 1.44,
		precio: 2900,
		imagen: 'pisos/linen.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 5,
		categoria: 'pisos',
		nombre: 'Artec',
		medida: '60x60',
		caja: 1.44,
		precio: 2700,
		imagen: 'pisos/artec.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 6,
		categoria: 'pisos',
		nombre: 'Calacata',
		medida: '60x60',
		caja: 1.44,
		precio: 4300,
		imagen: 'pisos/calacata.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 7,
		categoria: 'pisos',
		nombre: 'Amur',
		medida: '60x60',
		caja: 1.44,
		precio: 3750,
		imagen: 'pisos/amur.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 8,
		categoria: 'pisos',
		nombre: 'Porfido',
		medida: '58x58',
		caja: 1.35,
		precio: 3200,
		imagen: 'pisos/porfido.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 9,
		categoria: 'pisos',
		nombre: 'Oxidum',
		medida: '60x60',
		caja: 1.44,
		precio: 4200,
		imagen: 'pisos/oxidum.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 10,
		categoria: 'pisos',
		nombre: 'Cleveland',
		medida: '23x120',
		caja: 1.12,
		precio: 4500,
		imagen: 'pisos/cleveland.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 11,
		categoria: 'pisos',
		nombre: 'Muse',
		medida: '50x100',
		caja: 1,
		precio: 4700,
		imagen: 'pisos/muse.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 12,
		categoria: 'pisos',
		nombre: 'Vermont',
		medida: '15x90',
		caja: 0.95,
		precio: 4400,
		imagen: 'pisos/vermont.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 13,
		categoria: 'vidrios',
		nombre: 'Vidrio Rojo',
		medida: '60x120',
		caja: 1.44,
		precio: 6300,
		imagen: 'pisos/vrojo.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 14,
		categoria: 'vidrios',
		nombre: 'Vidrio Turquesa',
		medida: '60x120',
		caja: 1.44,
		precio: 6300,
		imagen: 'pisos/vturquesa.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 15,
		categoria: 'vidrios',
		nombre: 'Vidrio Amarillo',
		medida: '60x120',
		caja: 1.44,
		precio: 6300,
		imagen: 'pisos/vamarillo.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 16,
		categoria: 'vidrios',
		nombre: 'Vidrio Blanco',
		medida: '60x120',
		caja: 1.44,
		precio: 6300,
		imagen: 'pisos/vblanco.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 17,
		categoria: 'vidrios',
		nombre: 'Vidrio Negro',
		medida: '60x120',
		caja: 1.44,
		precio: 6300,
		imagen: 'pisos/vnegro.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 18,
		categoria: 'vidrios',
		nombre: 'Vidrio Vison',
		medida: '60x120',
		caja: 1.44,
		precio: 6300,
		imagen: 'pisos/vvison.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 19,
		categoria: 'ceramicos',
		nombre: 'Ceramico Subway Azul',
		medida: '10x20',
		caja: 1,
		precio: 4200,
		imagen: 'pisos/sub-azul.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 20,
		categoria: 'ceramicos',
		nombre: 'Ceramico Subway Blanco',
		medida: '10x20',
		caja: 1,
		precio: 4200,
		imagen: 'pisos/sub-blanco.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 21,
		categoria: 'ceramicos',
		nombre: 'Ceramico Subway Negro',
		medida: '10x20',
		caja: 1,
		precio: 4200,
		imagen: 'pisos/sub-negro.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 22,
		categoria: 'ceramicos',
		nombre: 'Ceramico Subway Rojo',
		medida: '10x20',
		caja: 1,
		precio: 4200,
		imagen: 'pisos/sub-rojo.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 23,
		categoria: 'piedras',
		nombre: 'Piedra Amarilla',
		medida: '20xLL',
		caja: 1,
		precio: 2600,
		imagen: 'pisos/piedra-amarilla.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 24,
		categoria: 'piedras',
		nombre: 'Piedra Beige',
		medida: '20x30',
		caja: 0.49,
		precio: 3500,
		imagen: 'pisos/piedra-beige.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 25,
		categoria: 'piedras',
		nombre: 'Piedra Muro',
		medida: 'irregular',
		caja: 1,
		precio: 1600,
		imagen: 'pisos/piedra-muro.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 26,
		categoria: 'piedras',
		nombre: 'Piedra San Juan',
		medida: '20xLL',
		caja: 1,
		precio: 2,
		imagen: 'pisos/piedra-sanjuan.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 27,
		categoria: 'piedras',
		nombre: 'Piedra Verde',
		medida: '20x35',
		caja: 0.48,
		precio: 3500,
		imagen: 'pisos/piedra-verde.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
];

export const getFetch = new Promise((resolve) => {
	setTimeout(() => {
		resolve(productos);
	}, 3000);
});

const producto = {
	id: 6,
	categoria: 'pisos',
	nombre: 'Calacata',
	medida: '60x60',
	caja: 1.44,
	precio: 4300,
	imagen: 'pisos/calacata.jpg',
	cantidad: 0,
	pegamento: false,
	pastina: false,
};

export const getFetchUno = new Promise((resolve) => {
	setTimeout(() => {
		resolve(producto);
	}, 2000);
});
