const productos = [
	{
		id: 1,
		categoria: 'pisos',
		nombre: 'Carrara',
		medida: '60x120',
		caja: 1.44,
		precio: 5000,
		imagen: 'pisos/carrara.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 2,
		categoria: 'pisos',
		nombre: 'Onix',
		medida: '60x60',
		caja: 1.44,
		precio: 4200,
		imagen: 'pisos/onix.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 3,
		categoria: 'pisos',
		nombre: 'Bauhaus',
		medida: '58x58',
		caja: 1.35,
		precio: 2800,
		imagen: 'pisos/bauhaus.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 4,
		categoria: 'pisos',
		nombre: 'Linen',
		medida: '60x60',
		caja: 1.44,
		precio: 2900,
		imagen: 'pisos/linen.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 5,
		categoria: 'pisos',
		nombre: 'Artec',
		medida: '60x60',
		caja: 1.44,
		precio: 2700,
		imagen: 'pisos/artec.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 6,
		categoria: 'pisos',
		nombre: 'Calacata',
		medida: '60x60',
		caja: 1.44,
		precio: 4300,
		imagen: 'pisos/calacata.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 7,
		categoria: 'pisos',
		nombre: 'Amur',
		medida: '60x60',
		caja: 1.44,
		precio: 3750,
		imagen: 'pisos/amur.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 8,
		categoria: 'pisos',
		nombre: 'Porfido',
		medida: '58x58',
		caja: 1.35,
		precio: 3200,
		imagen: 'pisos/porfido.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 9,
		categoria: 'pisos',
		nombre: 'Oxidum',
		medida: '60x60',
		caja: 1.44,
		precio: 4200,
		imagen: 'pisos/oxidum.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 10,
		categoria: 'pisos',
		nombre: 'Cleveland',
		medida: '23x120',
		caja: 1.12,
		precio: 4500,
		imagen: 'pisos/cleveland.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 11,
		categoria: 'pisos',
		nombre: 'Muse',
		medida: '50x100',
		caja: 1,
		precio: 4700,
		imagen: 'pisos/muse.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 12,
		categoria: 'pisos',
		nombre: 'Vermont',
		medida: '15x90',
		caja: 0.95,
		precio: 4400,
		imagen: 'pisos/vermont.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 13,
		categoria: 'vidrios',
		nombre: 'Vermont',
		medida: '15x90',
		caja: 0.95,
		precio: 4400,
		imagen: 'pisos/vermont.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 14,
		categoria: 'ceramicos',
		nombre: 'Muse',
		medida: '50x100',
		caja: 1,
		precio: 4700,
		imagen: 'pisos/muse.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
	{
		id: 15,
		categoria: 'piedras',
		nombre: 'Oxidum',
		medida: '60x60',
		caja: 1.44,
		precio: 4200,
		imagen: 'pisos/oxidum.jpg',
		cantidad: 0,
		pegamento: false,
		pastina: false,
	},
];

export const getFetch = new Promise((resolve) => {
	setTimeout(() => {
		resolve(productos);
	}, 3000);
});

const producto = {
	id: 6,
	categoria: 'pisos',
	nombre: 'Calacata',
	medida: '60x60',
	caja: 1.44,
	precio: 4300,
	imagen: 'pisos/calacata.jpg',
	cantidad: 0,
	pegamento: false,
	pastina: false,
};

export const getFetchUno = new Promise((resolve) => {
	setTimeout(() => {
		resolve(producto);
	}, 2000);
});
